# Generated by Django 4.2.7 on 2024-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
